name = "quick-ref-push-worker"
main = "push-worker-index.js"
compatibility_date = "2024-01-01"

# KV (購読情報を保存する)
kv_namespaces = [
  { binding = "PUSH_KV", id = "b324458a3ba34fefa8d7ca1c25d3148e" }
]

# 環境変数（Cloudflare Dashboard の Variables に設定）
[vars]
AUTH_TOKEN = "quick-ref-secret-2026-nori-xyz"
VAPID_PUBLIC_KEY = "BIYDS1WrYB4coViec9AnOG2NswgsAaGzPeq6whmRKdzt_VUOHRoWN2Pc5CTQOVMcBQGFXtP4k4n1KbbMrOADtUk"
VAPID_PRIVATE_KEY = "otz-Br2S81bahqhr7uOzt4C96Do4T5sQXqvwrTSgeaM"
VAPID_SUBJECT = "mailto:arielfortuneoffice@gmail.com"
CORS_ORIGIN = "*"

# Cron（毎朝のデイリーレビュー通知）
[triggers]
crons = ["0 8 * * *"]   # 毎朝 8:00 に実行
